---
title: "Ecological Metagenome-derived Reference Genomes and Traits (EMERGENT)"
---

This is the project web site for Ecological Metagenome-derived Reference Genomes and Traits (EMERGENT), a NSF LTER Synthesis working group.

### Project Summary

Our climate crisis, resulting from changes in interacting climate variables (temperature, rainfall, atmospheric chemistry) over the last century, has impacted all ecosystems on the surface of the Earth. With modern DNA sequencing techniques it is now possible to simultaneously sample thousands of different species, providing a window into the diverse soil organismal community and their ecological traits. While often the sequence data is stored at international nucleotide sequence data centers (NCBI, EBI, DDBJ), these databases do not have the resources to process and integrate microbiome data. This results in the compartmentalization of studies, failure to effectively utilize data across sites, and repetitive development of similar analytical pipelines across multiple research groups. Our working group proposes to alleviate some of these bottlenecks to make greater use of the existing genetic data to address climate related-questions and provide reference species (genomes) for future research. Our work will advance efforts to harmonize molecular information for microbial taxa and their functional traits, streamline their use in syntheses with related ecosystem level data, and enable future metagenomic studies to leverage EDI environmental data, spurring future microbial ecology research at LTER sites.

### Principal Investigators

Jeff Blanchard, Janet Jansson, Jason McDermott, Margaret O'Brien, Jorge Rodriguez and Lee Stanish

### Participants & Collaborators

Steven Allison, Emiley Eloe-Fadrosh, Sarah Evans, Dawson Fairbanks, Rachel Gallery, Adina Howe, Heather Kittredge, Linda Kinkel, David Myrold, Jennifer Pett-Ridge, William Rodriguez-Reillo, Tina Takacs-Vesbach, Kate Lajtha, Ashley Shade, Kristen Vanderbilt and Emery Boose

Award Date: January 9, 2020